# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '12.x'
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test-headless'
    workingDir: '$(Build.SourcesDirectory)'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run lint'
    workingDir: '$(Build.SourcesDirectory)'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish nodejs code coverage results'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(Build.SourcesDirectory)/coverage'
    failIfCoverageEmpty: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Build.SourcesDirectory)/coverage/**/RESULTS.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Angular'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'build --prod'
    workingDir: '$(Build.SourcesDirectory)'
- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'package'
    publishLocation: 'Container'